blog/app/models/user.py
from app.extensions import db
from .db_base import DB  # 导入模型操作的基类
from flask import current_app  # 使用当前的app
from werkzeug.security import generate_password_hash, check_password_hash  # 导入hash加密模块
from itsdangerous import TimedJSONWebSignatureSerializer as Seralize  # 导入生成token的模块
from app.extensions import login_manager
from flask_login import UserMixin
from datetime import datetime
from .posts import Posts

class User(UserMixin, db.Model, DB):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(12), index=True)
    password_hash = db.Column(db.String(120))
    email = db.Column(db.String(50), index=True)
    age = db.Column(db.Integer, default=18)
    sex = db.Column(db.Boolean, default=True)
    timestamp = db.Column(db.DateTime, default=datetime.utcnow())  # 时间
    attention = db.Column(db.Text, default='0')
    icon = db.Column(db.String(70), default='default.jpg')
    confirm = db.Column(db.Boolean, default=False)  # 账号是否激活，默认未激活
    """
    posts 是当前user模型的关联属性，可以通过当前用户获取该用户发表的博客
    参数：
        Posts: 建立关联的模型
        backref: 给关联的模型添加字段属性 user
        lazy： 加载时机， 返回查询集，可以再次进行二次过滤：User.query+过滤器，如果
                不加lazy属性，则返回结果的列表
    """
    posts = db.relationship('Posts', backref='user', lazy='dynamic')
    comment = db.relationship(
        'Comment', backref='comment_user', lazy='dynamic')
    # secondary 是多对多时指定数据的中间表
    # backref给另一方的多设置查询结果为查询集，可以进行查询结果的过滤
    favorites = db.relationship('Posts', secondary='collections', backref=db.backref(
        'users', lazy='dynamic'), lazy='dynamic')

    @property
    def password(self):
        raise AttributeError('该属性不可读')

    # 生成加密密码
    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    # 验证密码正确性
    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    # 生成token的方法
    def generate_token(self):
        # 默认token有效期是一小时，可以在Seralize原代码修改
        token = Seralize(current_app.config['SECRET_KEY'])
        # token中携带ID字段
        return token.dumps({'id': self.id})

    # 验证token并进行账号的激活
    @staticmethod
    def check_token(token):
        s = Seralize(current_app.config['SECRET_KEY'])
        # 在解析和激活操作过程中，有任何异常都会激活失败
        try:
            id = s.loads(token)['id']
            u = User.query.get(int(id))
            if not u.confirm:
                u.confirm = True
                u.save()
            return True
        except:
            return False

    # 判断是否收藏的方法
    def is_favorite(self, id):
            favorites = self.favorites.all()
            for f in favorites:
                if f.id == id:
                    return True
            return False

    # 执行收藏的方法
    def add_favorite(self, id):
        self.favorites.append(Posts.query.get(id))
        db.session.commit()


    # 取消收藏的方法
    def del_favorite(self, id):
        self.favorites.remove(Posts.query.get(id))
        db.session.commit()



# 回调函数，实时获取user表中的数据
@login_manager.user_loader  # 这个装饰器会自动查找最新的User对象
def user_loader(userid):
    return User.query.get(int(userid))

blog/app/forms/user.py
from flask_wtf import FlaskForm
from wtforms.fields import SubmitField, StringField, PasswordField, FileField
from wtforms.validators import ValidationError, DataRequired, Length, Email, equal_to
from flask_wtf.file import FileRequired, FileAllowed
from app.models import User


# 表单注册类
class Register(FlaskForm):
    username = StringField('用户名', validators=[DataRequired(message='用户名不能为空'),
                                              Length(min=6, max=12, message='用户名不能超过50个字')],
                           render_kw={'placeholder': '请输入用户名'})
    password = PasswordField('密码', validators=[DataRequired(message='密码不能为空'),
                                               Length(min=6, max=12, message='密码在6到12位')],
                             render_kw={'placeholder': '请输入密码'})
    password_two = PasswordField('确认密码', validators=[equal_to('password', message='两次密码不一致')],
                                 render_kw={'placeholder': '请输入确认密码'})
    email = StringField('邮箱', validators=[DataRequired(message='邮箱不能为空'), Email(message='请输入正确的邮箱')],
                        render_kw={'placeholder': '请输入邮箱'})
    submit = SubmitField('注册')

    # 判断用户名和邮箱是否唯一
    def validate_username(self, field):
        if User.query.filter_by(username=field.data).first():
            raise ValidationError('该用户已存在')

    def validate_email(self, field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('该邮箱已存在')


# 登陆表单
class Login(FlaskForm):
    username = StringField('用户名', validators=[DataRequired(message='用户名不能为空'),
                                              Length(min=6, max=12, message='用户名在6到12位')],
                           render_kw={'placeholder': '请输入用户名'})
    password = PasswordField('密码', validators=[DataRequired(message='密码不能为空'),
                                               Length(min=6, max=12, message='密码在6到12位')],
                             render_kw={'placeholder': '请输入密码'})
    submit = SubmitField('登陆')

    # 判断用户名是否存在
    def validate_username(self, field):
        if not User.query.filter_by(username=field.data).first():
            raise ValidationError('该用户不存在')


# 修改头像类
class Icon(FlaskForm):
    icon = FileField('头像', validators=[FileRequired(message='头像不能为空'),
                                       FileAllowed(['jpg', 'jpeg', 'gif', 'png'], message='请上传正确的格式图片')])
    submit = SubmitField('修改')


# 修改用户名类
class Username(FlaskForm):
    username = StringField('当前用户名', validators=[DataRequired(message='用户名不能为空'),
                                                Length(min=6, max=12, message='用户名在6到12位')],
                           render_kw={'placeholder': '请输入用户名'})
    password = PasswordField('密码', validators=[DataRequired(message='密码不能为空'),
                                               Length(min=6, max=12, message='密码在6到12位')],
                             render_kw={'placeholder': '请输入密码'})
    username_name = StringField('新用户名', validators=[DataRequired(message='用户名不能为空'),
                                                    Length(min=6, max=12, message='用户名在6到12位')],
                                render_kw={'placeholder': '请输入用户名'})
    submit = SubmitField('修改')


# 修改密码类
class ChangePassword(FlaskForm):
    username = StringField('当前用户名', validators=[DataRequired(message='用户名不能为空'),
                                                Length(min=6, max=12, message='用户名在6到12位')],
                           render_kw={'placeholder': '请输入用户名'})
    password_old = PasswordField('密码', validators=[DataRequired(message='密码不能为空'),
                                                   Length(min=6, max=12, message='密码在6到12位')],
                                 render_kw={'placeholder': '请输入密码'})
    password = PasswordField('密码', validators=[DataRequired(message='密码不能为空'),
                                               Length(min=6, max=12, message='密码在6到12位')],
                             render_kw={'placeholder': '请输入密码'})
    password_two = PasswordField('确认密码', validators=[equal_to('password', message='两次密码不一致')],
                                 render_kw={'placeholder': '请输入确认密码'})
    submit = SubmitField('修改')


# 修改邮箱类
class Change_email(FlaskForm):
    username = StringField('当前用户名', validators=[DataRequired(message='用户名不能为空'),
                                                Length(min=6, max=12, message='用户名在6到12位')],
                           render_kw={'placeholder': '请输入用户名'})
    password = PasswordField('密码', validators=[DataRequired(message='密码不能为空'),
                                               Length(min=6, max=12, message='密码在6到12位')],
                             render_kw={'placeholder': '请输入密码'})
    email_old = StringField('邮箱', validators=[DataRequired(message='邮箱不能为空'), Email(message='请输入正确的邮箱')],
                            render_kw={'placeholder': '请输入邮箱'})
    email_new = StringField('邮箱', validators=[DataRequired(message='邮箱不能为空'), Email(message='请输入正确的邮箱')],
                            render_kw={'placeholder': '请输入邮箱'})
    submit = SubmitField('修改')


# 找回密码
class Recover_password(FlaskForm):
    email = StringField('邮箱', validators=[DataRequired(message='邮箱不能为空'), Email(message='请输入正确的邮箱')],
                        render_kw={'placeholder': '请输入邮箱'})
    submit = SubmitField('确认')



class NewPassword(FlaskForm):
    password = PasswordField('密码', validators=[DataRequired(message='密码不能为空'),
                                               Length(min=6, max=12, message='密码在6到12位')],
                             render_kw={'placeholder': '请输入密码'})
    password_two = PasswordField('确认密码', validators=[equal_to('password', message='两次密码不一致')],
                                 render_kw={'placeholder': '请输入确认密码'})
    submit = SubmitField('确认')

blog/app/views/user.py
from flask import Blueprint, render_template, flash, redirect, url_for, request
from app.forms import Register, Login  # 导入表单注册类,登陆类
from app.forms.user import Icon, Username, ChangePassword, Change_email, Recover_password, NewPassword
from app.models import User  # 导入user模型类
from app.mail import send_mail
from flask import current_app
from flask_login import login_required, current_user, login_user, logout_user
from flask_uploads import UploadSet, configure_uploads, patch_request_class, IMAGES
import os

user = Blueprint('user', __name__)

# 注册的视图函数
'''
注册功能步骤
1. 判断用户名和邮箱是否唯一
2. 将接收到的表单正确数据进行存储（密码加密存储）
3. 生成token字符串（让用户点击账户激活时，我们知道是谁来激活的）
4. 配置发送邮件的代码
5. 发送邮件携带的token
6. 用户点击进行账号激活
'''


# 注册视图函数
@user.route('/register/', methods=['POST', 'GET'])
def register():
    form = Register()
    if form.validate_on_submit():
        # try:
        # password是加密后的密码
        info = User(username=form.username.data, password=form.password.data, email=form.email.data)
        info.save()
        # 获取token字符串
        token = info.generate_token()
        # 发送邮件
        send_mail('邮件激活', info.email, 'activate', username=info.username, token=token,
                  endpoint='user.activate')
        flash('注册成功，请前往邮箱进行账号的激活')
        return redirect(url_for('user.login'))
        # except:
        #     flash('用户注册失败')
    return render_template('user/register.html', form=form)


# 邮件激活的视图函数
@user.route('/activate/<token>/')
def activate(token):
    if User.check_token(token):
        flash('激活成功')
    else:
        flash('激活失败')
    return redirect(url_for('user.login'))


# 登陆的视图函数
"""
接收到用户数据以后
验证密码是否正确
正确则保持用户登陆状态
错误则重新登陆
"""


@user.route('/login/', methods=['POST', 'GET'])
def login():
    form = Login()
    if form.validate_on_submit():
        try:
            u = User.query.filter(User.username == form.username.data).first()
            if not u.check_password(form.password.data):
                flash('密码错误，请输入正确的密码')
            elif not u.confirm:
                flash('您还未激活，不能登陆')
            else:
                login_user(u)  # 维持当前的登录状态
                return redirect(url_for('main.index'))
        except:
            flash('登陆失败，请重新登陆')
    return render_template('user/login.html', form=form)


# 退出方法
@user.route('/logout/')
def logout():
    logout_user()  # 退出登录状态
    flash('退出成功')
    return redirect(url_for('main.index'))


# 设置随机名称的函数
def random_name(suffix, length=64):
    import string, random
    pattern = string.ascii_letters + string.digits
    return ''.join(random.choices(pattern, k=length)) + suffix


# 添加修改头像
@user.route('/change_icon/', methods=['POST', 'GET'])
def change_icon():
    from PIL import Image
    form = Icon()
    new_name = None
    # img_url = current_user
    if not current_user.is_authenticated:
        flash('请先登录再修改')
    # data = User.query.filter(User.username == current_user)
    elif form.validate_on_submit():
        file = request.files.get('icon')
        suffix = os.path.splitext(file.filename)[-1]
        new_name = random_name(suffix)
        UPLOD_FOLDER = os.path.join(os.getcwd(), 'app\\static\\upload')
        path = os.path.join(UPLOD_FOLDER, new_name)
        file.save(path)
        img = Image.open(path)
        img.thumbnail((100, 100))
        img.save(path)
        current_user.icon = new_name
        User.save(current_user)
    return render_template('user/change_icon.html', form=form, filename=new_name)


# 显示个人信息
@user.route('/my_info/')
@login_required
def my_info():
    u = User.query.get(current_user.id)
    return render_template('user/my_info.html', u=u)


# 修改用户个人用户名
@user.route('/change_account/', methods=['POST', 'GET'])
def change_username():
    form = Username()
    if current_user.is_authenticated:
        logout_user()
    if form.validate_on_submit():
        try:
            u = User.query.filter(User.username == form.username.data).first()
            if not u:
                flash('用户名不存在，请输入正确的用户名')
            if not u.check_password(form.password.data):
                flash('密码错误，请输入正确的密码')
            if User.query.filter(User.username == form.username_name.data).first():
                flash('新用户名已存在，请输入其他的用户名')
            else:
                u.username = form.username_name.data
                User.save(u)
                flash('修改成功，请登录')
                return redirect(url_for('user.login'))
        except:
            flash('修改失败，请重新修改')
    return render_template('user/change_username.html', form=form)


# 修改用户密码
@user.route('/change_password/', methods=['POST', 'GET'])
def change_password():
    form = ChangePassword()
    if current_user.is_authenticated:
        logout_user()
    if form.validate_on_submit():
        try:
            u = User.query.filter(User.username == form.username.data).first()
            if not u:
                flash('用户名不存在，请输入正确的用户名')
            if not u.check_password(form.password_old.data):
                flash('旧密码错误，请输入正确的密码')
            else:
                u.password = form.password.data
                User.save(u)
                flash('修改成功，请登录')
                return redirect(url_for('user.login'))
        except:
            flash('修改失败，请重新修改')
    return render_template('user/change_password.html', form=form)


# 修改邮箱
@user.route('/change_email/', methods=['POST', 'GET'])
def change_email():
    form = Change_email()
    if form.validate_on_submit():
        try:
            u = User.query.filter(User.username == form.username.data).first()
            if not u.check_password(form.password.data):
                flash('密码错误，请输入正确的密码')
            if u.email != form.email_old.data:
                flash('之前的邮箱不正确')
            if User.query.filter(User.email == form.email_new.data).first():
                flash('新邮箱已被其他账号绑定，请更改')
            else:
                u.email = form.email_new.data
                u.confirm = False
                u.save()
                # 获取token字符串
                token = u.generate_token()
                # 发送邮件
                send_mail('邮件激活', u.email, 'activate', username=u.username, token=token,
                          endpoint='user.activate')
                flash('修改成功，请前往邮箱进行账号的激活')
                return redirect(url_for('user.login'))
        except:
            flash('修改失败，请重新修改')
    return render_template('user/change_email.html', form=form)


# 邮件激活的视图函数
@user.route('/activate_password/<token>/', methods=['POST', 'GET'])
def activate_password(token):
    form = NewPassword()
    if User.check_token(token):
        from itsdangerous import TimedJSONWebSignatureSerializer as Seralize  # 导入生成token的模块
        s = Seralize(current_app.config['SECRET_KEY'])
        # 在解析和激活操作过程中，有任何异常都会激活失败
        id = s.loads(token)['id']
        if form.validate_on_submit():
            u = User.query.get(int(id))
            u.password = form.password.data
            User.save(u)
            flash('修改成功，请登录')
            return redirect(url_for('user.login'))
        return render_template('user/password_recover.html', form=form)
    else:
        flash('找回密码失败')
    return render_template('user/password_recover.html', form=form)


@user.route('/recover_password/', methods=['POST', 'GET'])
def recover_password():
    form = Recover_password()
    if form.validate_on_submit():
        u = User.query.filter(User.email == form.email.data).first()
        if not u:
            flash('邮箱不正确')
            return redirect(url_for('user.login'))
        else:
            # 获取token字符串
            token = u.generate_token()
            # 发送邮件
            send_mail('邮件激活', u.email, 'activate_password', username=u.username, token=token,
                      endpoint='user.activate_password')
            flash('修改密码邮件已发送，请去邮箱确认')
            return redirect(url_for('user.login'))
    return render_template('user/recover_password.html', form=form)


# @user.route('/password_recover/')
# def password_recover():
#     form = NewPassword()
#     pass

blog/app/templates/user/change_email.html
{% extends'common/base.html' %}
{% block title %}
    修改用户名
{% endblock %}

{% block page_content %}
        {% from 'bootstrap/wtf.html' import quick_form %}
    <h2>修改用户名</h2>

    <div class="row">
  <div class="col-md-8">.col-md-8</div>
  <div class="col-md-4">{{ quick_form(form) }}</div>
</div>
{% endblock %}

blog/app/templates/user/change_icon.html
{% extends'common/base.html' %}
{% block title %}
    修改头像
{% endblock %}

{% block page_content %}
    {% from 'bootstrap/wtf.html' import quick_form %}
    {#    <h2>修改头像</h2>#}

    <div class="row">
        {#  <div class="col-md-8">.col-md-8</div>#}
        <div class="col-md-8">
            {% if filename %}
                <h3>修改后头像</h3>
                <img src="{{ url_for('static', filename='upload/'+filename, _external=True) }}" alt="">
            {% else %}
                <h3>当前的头像</h3>
                {% if current_user.icon %}
                    <img src="{{ url_for('static', filename='upload/'+current_user.icon, _external=True) }}" alt="">
                {% else %}
                    <img src="{{ url_for('static', filename='upload/default.jgp', _external=True) }}" alt="">
                {% endif %}
            {% endif %}
        </div>
        <div class="col-md-4">{{ quick_form(form) }}</div>
    </div>
{% endblock %}

blog/app/templates/user/change_password.html
{% extends'common/base.html' %}
{% block title %}
    修改密码
{% endblock %}

{% block page_content %}
        {% from 'bootstrap/wtf.html' import quick_form %}
    <h2>修改密码</h2>

    <div class="row">
  <div class="col-md-8">.col-md-8</div>
  <div class="col-md-4">{{ quick_form(form) }}</div>
</div>
{% endblock %}

blog/app/templates/user/change_username.html
{% extends'common/base.html' %}
{% block title %}
    修改用户名
{% endblock %}

{% block page_content %}
        {% from 'bootstrap/wtf.html' import quick_form %}
    <h2>修改用户名</h2>

    <div class="row">
  <div class="col-md-8">.col-md-8</div>
  <div class="col-md-4">{{ quick_form(form) }}</div>
</div>
{% endblock %}

blog/app/templates/user/login.html
{% extends'common/base.html' %}
{% block title %}
    登陆
{% endblock %}

{% block page_content %}
    {% from 'bootstrap/wtf.html' import quick_form %}
    <h3>测试账号</h3>
    <h3>账号：xuxy19；密码：123456</h3>
    <h3>账号：xuxy20；密码：123456</h3>

    <div class="row">
        <div class="col-md-8"><img class="media-object" width="200px"
                                   src="{{ url_for('static', filename='img/'+'advertisement.jpg', _external=True) }}"
                                   alt="...">
        </div>
        <div class="col-md-4">{{ quick_form(form) }}</div>
    </div>
    <div align="right"><a href="{{ url_for('user.recover_password') }}" target="_blank">
        <button type="button" class="" id="addnew">忘记密码</button>
    </a></div>
{% endblock %}

blog/app/templates/user/my_info.html
{% extends'common/base.html' %}
{% block title %}
    个人信息
{% endblock %}
{% block page_content %}
    <caption><h2>我的信息</h2></caption>
        <tr align="center">
            <td>姓名</td>
            <td>{{ u.username }}</td>
        </tr>
    <br>
        <tr align="center">
            <td>性别</td>
            <td>{% if u.sex %}男{% else %}女{% endif %}</td>
        </tr>

{% endblock %}

blog/app/templates/user/password_recover.html
{% extends'common/base.html' %}
{% block title %}
    找回密码
{% endblock %}

{% block page_content %}
        {% from 'bootstrap/wtf.html' import quick_form %}
    <h2>输入新密码</h2>

    <div class="row">
  <div class="col-md-8">.col-md-8</div>
  <div class="col-md-4">{{ quick_form(form) }}</div>
</div>
{% endblock %}

blog/app/templates/user/recover_password.html
{% extends'common/base.html' %}
{% block title %}
    找回密码
{% endblock %}

{% block page_content %}
        {% from 'bootstrap/wtf.html' import quick_form %}
    <h2>使用邮箱找回密码</h2>

    <div class="row">
  <div class="col-md-8">.col-md-8</div>
  <div class="col-md-4">{{ quick_form(form) }}</div>
</div>
{% endblock %}

blog/app/templates/user/register.html
{% extends'common/base.html' %}
{% block title %}
    注册
{% endblock %}

{% block page_content %}
        {% from 'bootstrap/wtf.html' import quick_form %}
    <h2>注册</h2>

    <div class="row">
  <div class="col-md-8">.col-md-8</div>
  <div class="col-md-4">{{ quick_form(form) }}</div>
</div>
{% endblock %}