blog/app/models/posts.py
from app.extensions import db
from .db_base import DB  # 导入模型操作的基类
from datetime import datetime


class Posts(db.Model, DB):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(50), index=True)
    article = db.Column(db.Text)
    pid = db.Column(db.Integer, default=0)  # 无限级分类，多级评论用，comment id
    path = db.Column(db.String(255), default='0,')
    visit = db.Column(db.Integer, default=0)  # 访问量
    timestamp = db.Column(db.DateTime, default=datetime.utcnow())  # 时间
    state = db.Column(db.Boolean, default=True)  # 是否设为他人可见
    uid = db.Column(db.Integer, db.ForeignKey('user.id'))  # 添加外键，可以通过博客获取作者，也可以通过作者查询博客

    comment = db.relationship('Comment', backref='post', lazy='dynamic')

blog/app/forms/posts.py
from flask_wtf import FlaskForm
from wtforms.fields import SubmitField, StringField, TextAreaField, BooleanField, RadioField
from wtforms.validators import ValidationError, DataRequired, Length, Email, equal_to
from app.models import Posts


# 发表博客类
class SendPosts(FlaskForm):
    title = StringField('标题', validators=[DataRequired(message='标题不能为空'),
                                          Length(min=1, max=50, message='标题不能超过50字')],
                        render_kw={'placeholder': '请输入标题'})
    article = TextAreaField('内容', validators=[DataRequired(message='内容不能为空')],
                            render_kw={'placeholder': '请输入内容'})
    state = RadioField('是否他人可见', choices=[('1', '是'), ('0', '否')], validators=[DataRequired()])
    # state = BooleanField('是否设为他人可见', default='checked', validators=[DataRequired()])
    submit = SubmitField('发表')


# 博客操作类
class ChangePosts(FlaskForm):
    delete = SubmitField('删除')
    change = SubmitField('修改')
    state = RadioField('是否他人可见', choices=[('1', '是'), ('0', '否')], validators=[DataRequired()])
    attention = SubmitField('关注')

blog/app/views/owncenter.py
from flask import render_template, Blueprint, request, current_app, flash, redirect, url_for
from flask_login import login_required, current_user
from app.models import Posts, Comment
from app.forms import SendPosts, SendComment
from datetime import datetime

own = Blueprint('owncenter', __name__)


@own.route('/posts_manager/')
@login_required  # 这个装饰器作用是必须登录状态才能执行方法
def posts_manager():
    try:
        page = int(request.args.get('page', 1))
    except:
        page = 1
    # 查出自己的博客并按时间降序进行展示
    pagination = Posts.query.filter(Posts.uid == current_user.get_id()).order_by(Posts.timestamp.desc()).paginate(
        page, current_app.config['PAGE_NUM'], False)
    # 获取当前页面所有数据
    data = pagination.items
    current_username = current_user.username
    return render_template('owncenter/posts_manager.html', data=data, pagination=pagination,
                           current_username=current_username)


# 博客管理 删除
@own.route('/posts_delete/<int:id>/')
@login_required
def posts_delete(id):
    Posts.query.get(id).delete()
    flash('博客删除成功！')
    return redirect(url_for('owncenter.posts_manager'))


# 收藏博客
@own.route('/posts_attention/<int:id>/')
@login_required
def posts_attention(id):
    # attention_list = current_user.attention.split(',')
    # if str(id) not in attention_list:
    #     attention_list.append(str(id))
    #     a = True
    # else:
    #     attention_list.remove(str(id))
    #     a = False
    # print(attention_list)
    # current_user.attention = ','.join([str(i) for i in attention_list])
    # current_user.save()
    # p = Posts.query.get(id)
    # 写评论
    form = SendComment()
    if form.validate_on_submit():
        info = Comment(article=form.article.data,
                       user_id=current_user.id, post_id=id)
        info.save()
        flash('评论成功')
    data = Comment.query.filter(Comment.post_id == id, Comment.comment_user == current_user).order_by(
        Comment.timestamp.desc()).limit(2)
    data_all = Comment.query.filter(Comment.post_id == id).order_by(
        Comment.timestamp.desc()).limit(100)
    return render_template('posts/page_detail.html', p=p, data_all=data_all, data=data, form=form)


# 我的收藏
@own.route('/my_attention/', methods=['POST', 'GET'])
@login_required
def my_attention():
    try:
        page = int(request.args.get('page', 1))
    except:
        page = 1
    # 查出我收藏的博客并按收藏时间进行展示
    # attention_list = current_user.attention.split(',')
    # pagination = Posts.query.filter(current_user.favorites.all()).order_by(
    #     Posts.timestamp.desc()).paginate(page, current_app.config['PAGE_NUM'], False)
    # print(pagination)

    # pagination = current_user.favorites.all().paginate(page, current_app.config['PAGE_NUM'], False)
    # # 获取当前页面所有数据
    # data = pagination.items
    # print(pagination)
    # print(data)
    # return render_template('main/index.html', p=data, pagination=pagination)
    data = current_user.favorites.all()
    # pagination = current_user.favorites.all().paginate(page, current_app.config['PAGE_NUM'], False)
    # print (current_user.favorites.posts_id)
    # data = pagination.items
    return render_template('owncenter/my_attention.html', p=data)


# 博客修改
@own.route('/edit_posts/<int:id>/', methods=['GET', 'POST'])
@login_required
def edit_posts(id):
    form = SendPosts()
    p = Posts.query.get(id)  # 通过博客id查询出博客对象
    if form.validate_on_submit():
        p.title = form.title.data
        p.article = form.article.data
        p.timestamp = datetime.utcnow()
        if form.state.data == '0':
            p.state = False
        else:
            p.state = True
        p.save()
        flash('博客修改成功！')
        # 重定向到博客管理
        return redirect(url_for('owncenter.posts_manager'))
    # 添加默认值
    form.title.data = p.title
    form.article.data = p.article
    return render_template('owncenter/edit_posts.html', form=form)


# 搜索我的博客
@own.route('/search_my_posts/', methods=['POST', 'GET'])
def search_my_posts():
    from sqlalchemy import or_  # 导入或操作
    search_info = request.form.get('search', '')
    if not search_info:
        # 接收分页时传递过来的search
        search_info = request.args.get('search', '')
    try:
        page = int(request.arges.get('search', 1))
    except:
        page = 1
    # 搜索范围是标题和内容，并且在展示的时候匹配的内容红色显示
    pagination = Posts.query.filter(or_(Posts.title.contains(search_info), Posts.article.contains(search_info)),
                                    Posts.uid == current_user.id).order_by(Posts.timestamp.desc()).paginate(
        page, current_app.config['PAGE_NUM'], False)
    data = pagination.items
    return render_template('posts/search_detail.html', data=data, search_info=search_info, pagination=pagination)

blog/app/views/posts.py
from flask import Blueprint, render_template, flash, redirect, url_for, request, current_app, jsonify
from app.forms import SendPosts  # 导入博客表单
from app.forms import SendComment
from app.forms.posts import ChangePosts
from flask_login import login_required, current_user
from app.models import Posts, User, Comment  # 导入博客模型类
from flask_login import current_user
from sqlalchemy import or_  # 导入或操作

posts = Blueprint('posts', __name__)


# 必须登录后才能发表博客，调用该方法
@posts.route('/send_posts/', methods=['POST', 'GET'])
def send_posts():
    form = SendPosts()
    if not current_user.is_authenticated:
        flash('请先登录再发表')
    elif form.validate_on_submit():
        # print(form.state.data)
        if form.state.data == '0':
            p = False
        else:
            p = True
        info = Posts(title=form.title.data,
                     article=form.article.data, user=current_user, state=p)
        # print(info.get_id())
        info.save()
        if not form.state.data:
            pass

        flash('发表成功')
        return redirect(url_for('posts.send_posts'))
    return render_template('posts/send_posts.html', form=form)


# 显示博客详情的方法
@posts.route('/posts_detail/<int:id>/', methods=['POST', 'GET'])
@login_required
def posts_detail(id):
    p = Posts.query.get(id)
    # a = False
    # if current_user.is_authenticated and (str(id) in current_user.attention.split(',')):
    #     a = True
    # 写评论
    form = SendComment()
    if form.validate_on_submit():
        info = Comment(article=form.article.data,
                       user_id=current_user.id, post_id=id)
        info.save()
        flash('评论成功')
    data = Comment.query.filter(Comment.post_id == id, Comment.comment_user == current_user).order_by(
        Comment.timestamp.desc()).limit(2)
    data_all = Comment.query.filter(Comment.post_id == id).order_by(
        Comment.timestamp.desc()).limit(100)
    return render_template('posts/page_detail.html', p=p, form=form, data=data, data_all=data_all)


# 博客收藏与取消收藏
@posts.route('/dofavorite/')
def dofavorite():
    try:
        # 将id转为int类型
        id = int(request.args.get('id'))
        # 判断是否收藏
        if current_user.is_favorite(id):
            current_user.del_favorite(id)
            return jsonify({'code': 100})
        else:
            current_user.add_favorite(id)
            return jsonify({'code': 200})
    except:
        return jsonify({'code': 500})


# 博客搜索
@posts.route('/search/', methods=['POST', 'GET'])
def search():
    search_info = request.form.get('search', '')
    if not search_info:
        # 接收分页时传递过来的search
        search_info = request.args.get('search', '')
    try:
        page = int(request.arges.get('search', 1))
    except:
        page = 1
    # 搜索范围是标题和内容，并且在展示的时候匹配的内容红色显示
    pagination = Posts.query.filter(or_(Posts.title.contains(search_info), Posts.article.contains(search_info)),
                                    Posts.pid == 0, Posts.state == True).order_by(Posts.timestamp.desc()).paginate(
        page, current_app.config['PAGE_NUM'], False)
    data = pagination.items
    return render_template('posts/search_detail.html', data=data, search_info=search_info, pagination=pagination)

blog/app/templates/posts/page_detail.html
{% extends'common/base.html' %}
{% block title %}
博客详情
{% endblock %}


{% block page_content %}
<div class="media-body">
    <h4 class="media-heading">{{ p.title }}</h4>
    {{ p.article|safe }}
</div>
<br>
<br>
<br>
<br>
<span style="float: right">
    <p><span>作者：{{ p.user.username }}</span></p>
    <P><span>发表时间：{{ moment(p.timestamp).format('Y-M-D H:m:s') }}</span></p>
</span>
<br>
<br>
{#              收藏/取消收藏#}
<!-- {% if current_user.is_authenticated %} -->
<!-- 
        <a href="{{ url_for('owncenter.posts_attention',id=p.id) }}">{% if a %}取消收藏{% else %}收藏{% endif %}</a>

        <br> -->
<p><span style="cursor: pointer;" onclick="favourite({{ p.id }})" id="f{{ p.id }}">
        {% if current_user.is_favorite(p.id) %}取消收藏
        {% else %}收藏{% endif %}
    </span></p>
<br>
<br>
{% from 'bootstrap/wtf.html' import quick_form %}
{{ quick_form(form) }}
<br>
{% endif %}
<br>
<hr>
<h1 style="color: aqua;">评论区</h1>
<br>
<h2 style="color: blue">我的评论(最新的三条)</h2>
<br>
{#    展示我的评论的样式#}
{% for row in data %}
{{ row.article|striptags|showEllipsis }}
<br>
<span style="float: right; font-size: 14px; color: aqua;">{{ moment(row.timestamp).fromNow() }}</span>
<br>
{% endfor %}
<br>
<br>
<h2 style="color: blue">所有评论(最新的100条)</h2>
<br>
{% for row in data_all %}
<div class="media-body">
    {{ row.article|safe }}
</div>
<br>
<br>
<span style="float: right">
    <p><span>评论人：{{ row.comment_user.username }}</span></p>
    <P><span>评论时间：{{ moment(row.timestamp).format('Y-M-D H:m:s') }}</span></p>
</span>
<br>
<br>
<hr>
<br>
{% endfor %}
{% endblock %}

{% block scripts %}
{{ super() }}
<script>
    function favourite(id) {
        var node = $('#f' + id);
        $.get({{ url_for('posts.dofavorite') }}, { 'id': id }, function(data, status) {
            console.log(data.code);
            if (data.code == 100) {
                node.text('收藏')
            } if (data.code == 200) {
                node.text('取消收藏')
            }if (data.code == 500) {
                if (window.confirm('您是否还没有登录？\n请前去登录')) {
                    window.location.href = {{ url_for('user.login') }}}}
        });
    }


</script>

{% endblock %}

blog/app/templates/posts/search_detail.html
{% extends'common/base.html' %}
{% block title %}
    搜索
{% endblock %}

{% block page_content %}

    {#    展示博客的样式#}
    {% for row in data %}
        <div class="media">
            <div class="media-left media-middle">
                <a href="#">
{#                    <img class="media-object" src="..." alt="...">#}
                    <img class="media-object" src="{{ url_for('static', filename='upload/'+row.user.icon, _external=True) }}" alt="...">
                </a>
            </div>
            <a href="{{ url_for('posts.posts_detail', id=row.id) }}">
                <div class="media-body">
                    <h4 class="media-heading">{{ row.title|replace_red(search_info)|safe }}</h4>
                    {{ row.article|striptags|showEllipsis|replace_red(search_info)|safe }}
                </div>
                </a>
                <br>
                <span style="float: right; font-size: 14px; color: aqua;">{{ moment(row.timestamp).fromNow() }}</span>
        </div>
    {% endfor %}
    {#    分页#}
    {% from 'common/page_macro.html' import page_macro %}
    {{ page_macro('posts.search', pagination, search=search_info) }}
{% endblock %}

blog/app/templates/posts/send_posts.html
{% extends'common/base.html' %}
{% block title %}
    发表博客
{% endblock %}
{% block scripts %}
    {{ super() }}
    <script src="//cdn.ckeditor.com/4.4.6/standard/ckeditor.js"></script>

{% endblock %}
{% from 'bootstrap/wtf.html' import quick_form %}
{% block page_content %}
    <h2 class="page-header">发表博客</h2>

    <form action="" method="post">
        {{ form.csrf_token }}
        <h3>{{ form.title.label() }}</h3>
        {{ form.title(class="form-control",minlength=6,maxlength=12,placeholder='请输入标题6~12字之间') }}
        {% for err in form.title.errors %}
            <span style="color: red;">{{ err }}</span>
        {% endfor %}
        <br>
        <h3>{{ form.article.label() }}</h3>
        {{ form.article(class="ckeditor",minlength=6,maxlength=500) }}
        {% for err in form.article.errors %}
            <span style="color: red;">{{ err }}</span>
        {% endfor %}

        <br>
        <div>
            {{ form.state.label() }}：{{ form.state }}
        </div>
        <br>
        <button type="submit" class="btn btn-success">发表</button>
    </form>
{% endblock %}