blog/app/views/main.py
from flask import Blueprint, render_template, request, current_app
from app.models import Posts  # 导入博客模型类

# 首页的蓝本文件
main = Blueprint('main', __name__)


@main.route('/')
@main.route('/index/')
def index():
    try:
        page = int(request.args.get('page', 1))
    except:
        page = 1
    # 查出所有人可见的博客并按时间降序进行展示
    pagination = Posts.query.filter(Posts.pid == 0, Posts.state == True).order_by\
        (Posts.timestamp.desc()).paginate(page, current_app.config['PAGE_NUM'], False)
    # 获取当前页面所有数据
    data = pagination.items
    return render_template('main/index.html', p=data, pagination=pagination)

blog/app/views/owncenter.py
from flask import render_template, Blueprint, request, current_app, flash, redirect, url_for
from flask_login import login_required, current_user
from app.models import Posts, Comment
from app.forms import SendPosts, SendComment
from datetime import datetime

own = Blueprint('owncenter', __name__)


@own.route('/posts_manager/')
@login_required  # 这个装饰器作用是必须登录状态才能执行方法
def posts_manager():
    try:
        page = int(request.args.get('page', 1))
    except:
        page = 1
    # 查出自己的博客并按时间降序进行展示
    pagination = Posts.query.filter(Posts.uid == current_user.get_id()).order_by(Posts.timestamp.desc()).paginate(
        page, current_app.config['PAGE_NUM'], False)
    # 获取当前页面所有数据
    data = pagination.items
    current_username = current_user.username
    return render_template('owncenter/posts_manager.html', data=data, pagination=pagination,
                           current_username=current_username)


# 博客管理 删除
@own.route('/posts_delete/<int:id>/')
@login_required
def posts_delete(id):
    Posts.query.get(id).delete()
    flash('博客删除成功！')
    return redirect(url_for('owncenter.posts_manager'))


# 收藏博客
@own.route('/posts_attention/<int:id>/')
@login_required
def posts_attention(id):
    # attention_list = current_user.attention.split(',')
    # if str(id) not in attention_list:
    #     attention_list.append(str(id))
    #     a = True
    # else:
    #     attention_list.remove(str(id))
    #     a = False
    # print(attention_list)
    # current_user.attention = ','.join([str(i) for i in attention_list])
    # current_user.save()
    # p = Posts.query.get(id)
    # 写评论
    form = SendComment()
    if form.validate_on_submit():
        info = Comment(article=form.article.data,
                       user_id=current_user.id, post_id=id)
        info.save()
        flash('评论成功')
    data = Comment.query.filter(Comment.post_id == id, Comment.comment_user == current_user).order_by(
        Comment.timestamp.desc()).limit(2)
    data_all = Comment.query.filter(Comment.post_id == id).order_by(
        Comment.timestamp.desc()).limit(100)
    return render_template('posts/page_detail.html', p=p, data_all=data_all, data=data, form=form)


# 我的收藏
@own.route('/my_attention/', methods=['POST', 'GET'])
@login_required
def my_attention():
    try:
        page = int(request.args.get('page', 1))
    except:
        page = 1
    # 查出我收藏的博客并按收藏时间进行展示
    # attention_list = current_user.attention.split(',')
    # pagination = Posts.query.filter(current_user.favorites.all()).order_by(
    #     Posts.timestamp.desc()).paginate(page, current_app.config['PAGE_NUM'], False)
    # print(pagination)

    # pagination = current_user.favorites.all().paginate(page, current_app.config['PAGE_NUM'], False)
    # # 获取当前页面所有数据
    # data = pagination.items
    # print(pagination)
    # print(data)
    # return render_template('main/index.html', p=data, pagination=pagination)
    data = current_user.favorites.all()
    # pagination = current_user.favorites.all().paginate(page, current_app.config['PAGE_NUM'], False)
    # print (current_user.favorites.posts_id)
    # data = pagination.items
    return render_template('owncenter/my_attention.html', p=data)


# 博客修改
@own.route('/edit_posts/<int:id>/', methods=['GET', 'POST'])
@login_required
def edit_posts(id):
    form = SendPosts()
    p = Posts.query.get(id)  # 通过博客id查询出博客对象
    if form.validate_on_submit():
        p.title = form.title.data
        p.article = form.article.data
        p.timestamp = datetime.utcnow()
        if form.state.data == '0':
            p.state = False
        else:
            p.state = True
        p.save()
        flash('博客修改成功！')
        # 重定向到博客管理
        return redirect(url_for('owncenter.posts_manager'))
    # 添加默认值
    form.title.data = p.title
    form.article.data = p.article
    return render_template('owncenter/edit_posts.html', form=form)


# 搜索我的博客
@own.route('/search_my_posts/', methods=['POST', 'GET'])
def search_my_posts():
    from sqlalchemy import or_  # 导入或操作
    search_info = request.form.get('search', '')
    if not search_info:
        # 接收分页时传递过来的search
        search_info = request.args.get('search', '')
    try:
        page = int(request.arges.get('search', 1))
    except:
        page = 1
    # 搜索范围是标题和内容，并且在展示的时候匹配的内容红色显示
    pagination = Posts.query.filter(or_(Posts.title.contains(search_info), Posts.article.contains(search_info)),
                                    Posts.uid == current_user.id).order_by(Posts.timestamp.desc()).paginate(
        page, current_app.config['PAGE_NUM'], False)
    data = pagination.items
    return render_template('posts/search_detail.html', data=data, search_info=search_info, pagination=pagination)

blog/app/views/posts.py
from flask import Blueprint, render_template, flash, redirect, url_for, request, current_app, jsonify
from app.forms import SendPosts  # 导入博客表单
from app.forms import SendComment
from app.forms.posts import ChangePosts
from flask_login import login_required, current_user
from app.models import Posts, User, Comment  # 导入博客模型类
from flask_login import current_user
from sqlalchemy import or_  # 导入或操作

posts = Blueprint('posts', __name__)


# 必须登录后才能发表博客，调用该方法
@posts.route('/send_posts/', methods=['POST', 'GET'])
def send_posts():
    form = SendPosts()
    if not current_user.is_authenticated:
        flash('请先登录再发表')
    elif form.validate_on_submit():
        # print(form.state.data)
        if form.state.data == '0':
            p = False
        else:
            p = True
        info = Posts(title=form.title.data,
                     article=form.article.data, user=current_user, state=p)
        # print(info.get_id())
        info.save()
        if not form.state.data:
            pass

        flash('发表成功')
        return redirect(url_for('posts.send_posts'))
    return render_template('posts/send_posts.html', form=form)


# 显示博客详情的方法
@posts.route('/posts_detail/<int:id>/', methods=['POST', 'GET'])
@login_required
def posts_detail(id):
    p = Posts.query.get(id)
    # a = False
    # if current_user.is_authenticated and (str(id) in current_user.attention.split(',')):
    #     a = True
    # 写评论
    form = SendComment()
    if form.validate_on_submit():
        info = Comment(article=form.article.data,
                       user_id=current_user.id, post_id=id)
        info.save()
        flash('评论成功')
    data = Comment.query.filter(Comment.post_id == id, Comment.comment_user == current_user).order_by(
        Comment.timestamp.desc()).limit(2)
    data_all = Comment.query.filter(Comment.post_id == id).order_by(
        Comment.timestamp.desc()).limit(100)
    return render_template('posts/page_detail.html', p=p, form=form, data=data, data_all=data_all)


# 博客收藏与取消收藏
@posts.route('/dofavorite/')
def dofavorite():
    try:
        # 将id转为int类型
        id = int(request.args.get('id'))
        # 判断是否收藏
        if current_user.is_favorite(id):
            current_user.del_favorite(id)
            return jsonify({'code': 100})
        else:
            current_user.add_favorite(id)
            return jsonify({'code': 200})
    except:
        return jsonify({'code': 500})


# 博客搜索
@posts.route('/search/', methods=['POST', 'GET'])
def search():
    search_info = request.form.get('search', '')
    if not search_info:
        # 接收分页时传递过来的search
        search_info = request.args.get('search', '')
    try:
        page = int(request.arges.get('search', 1))
    except:
        page = 1
    # 搜索范围是标题和内容，并且在展示的时候匹配的内容红色显示
    pagination = Posts.query.filter(or_(Posts.title.contains(search_info), Posts.article.contains(search_info)),
                                    Posts.pid == 0, Posts.state == True).order_by(Posts.timestamp.desc()).paginate(
        page, current_app.config['PAGE_NUM'], False)
    data = pagination.items
    return render_template('posts/search_detail.html', data=data, search_info=search_info, pagination=pagination)

blog/app/views/user.py
from flask import Blueprint, render_template, flash, redirect, url_for, request
from app.forms import Register, Login  # 导入表单注册类,登陆类
from app.forms.user import Icon, Username, ChangePassword, Change_email, Recover_password, NewPassword
from app.models import User  # 导入user模型类
from app.mail import send_mail
from flask import current_app
from flask_login import login_required, current_user, login_user, logout_user
from flask_uploads import UploadSet, configure_uploads, patch_request_class, IMAGES
import os

user = Blueprint('user', __name__)

# 注册的视图函数
'''
注册功能步骤
1. 判断用户名和邮箱是否唯一
2. 将接收到的表单正确数据进行存储（密码加密存储）
3. 生成token字符串（让用户点击账户激活时，我们知道是谁来激活的）
4. 配置发送邮件的代码
5. 发送邮件携带的token
6. 用户点击进行账号激活
'''


# 注册视图函数
@user.route('/register/', methods=['POST', 'GET'])
def register():
    form = Register()
    if form.validate_on_submit():
        # try:
        # password是加密后的密码
        info = User(username=form.username.data, password=form.password.data, email=form.email.data)
        info.save()
        # 获取token字符串
        token = info.generate_token()
        # 发送邮件
        send_mail('邮件激活', info.email, 'activate', username=info.username, token=token,
                  endpoint='user.activate')
        flash('注册成功，请前往邮箱进行账号的激活')
        return redirect(url_for('user.login'))
        # except:
        #     flash('用户注册失败')
    return render_template('user/register.html', form=form)


# 邮件激活的视图函数
@user.route('/activate/<token>/')
def activate(token):
    if User.check_token(token):
        flash('激活成功')
    else:
        flash('激活失败')
    return redirect(url_for('user.login'))


# 登陆的视图函数
"""
接收到用户数据以后
验证密码是否正确
正确则保持用户登陆状态
错误则重新登陆
"""


@user.route('/login/', methods=['POST', 'GET'])
def login():
    form = Login()
    if form.validate_on_submit():
        try:
            u = User.query.filter(User.username == form.username.data).first()
            if not u.check_password(form.password.data):
                flash('密码错误，请输入正确的密码')
            elif not u.confirm:
                flash('您还未激活，不能登陆')
            else:
                login_user(u)  # 维持当前的登录状态
                return redirect(url_for('main.index'))
        except:
            flash('登陆失败，请重新登陆')
    return render_template('user/login.html', form=form)


# 退出方法
@user.route('/logout/')
def logout():
    logout_user()  # 退出登录状态
    flash('退出成功')
    return redirect(url_for('main.index'))


# 设置随机名称的函数
def random_name(suffix, length=64):
    import string, random
    pattern = string.ascii_letters + string.digits
    return ''.join(random.choices(pattern, k=length)) + suffix


# 添加修改头像
@user.route('/change_icon/', methods=['POST', 'GET'])
def change_icon():
    from PIL import Image
    form = Icon()
    new_name = None
    # img_url = current_user
    if not current_user.is_authenticated:
        flash('请先登录再修改')
    # data = User.query.filter(User.username == current_user)
    elif form.validate_on_submit():
        file = request.files.get('icon')
        suffix = os.path.splitext(file.filename)[-1]
        new_name = random_name(suffix)
        UPLOD_FOLDER = os.path.join(os.getcwd(), 'app\\static\\upload')
        path = os.path.join(UPLOD_FOLDER, new_name)
        file.save(path)
        img = Image.open(path)
        img.thumbnail((100, 100))
        img.save(path)
        current_user.icon = new_name
        User.save(current_user)
    return render_template('user/change_icon.html', form=form, filename=new_name)


# 显示个人信息
@user.route('/my_info/')
@login_required
def my_info():
    u = User.query.get(current_user.id)
    return render_template('user/my_info.html', u=u)


# 修改用户个人用户名
@user.route('/change_account/', methods=['POST', 'GET'])
def change_username():
    form = Username()
    if current_user.is_authenticated:
        logout_user()
    if form.validate_on_submit():
        try:
            u = User.query.filter(User.username == form.username.data).first()
            if not u:
                flash('用户名不存在，请输入正确的用户名')
            if not u.check_password(form.password.data):
                flash('密码错误，请输入正确的密码')
            if User.query.filter(User.username == form.username_name.data).first():
                flash('新用户名已存在，请输入其他的用户名')
            else:
                u.username = form.username_name.data
                User.save(u)
                flash('修改成功，请登录')
                return redirect(url_for('user.login'))
        except:
            flash('修改失败，请重新修改')
    return render_template('user/change_username.html', form=form)


# 修改用户密码
@user.route('/change_password/', methods=['POST', 'GET'])
def change_password():
    form = ChangePassword()
    if current_user.is_authenticated:
        logout_user()
    if form.validate_on_submit():
        try:
            u = User.query.filter(User.username == form.username.data).first()
            if not u:
                flash('用户名不存在，请输入正确的用户名')
            if not u.check_password(form.password_old.data):
                flash('旧密码错误，请输入正确的密码')
            else:
                u.password = form.password.data
                User.save(u)
                flash('修改成功，请登录')
                return redirect(url_for('user.login'))
        except:
            flash('修改失败，请重新修改')
    return render_template('user/change_password.html', form=form)


# 修改邮箱
@user.route('/change_email/', methods=['POST', 'GET'])
def change_email():
    form = Change_email()
    if form.validate_on_submit():
        try:
            u = User.query.filter(User.username == form.username.data).first()
            if not u.check_password(form.password.data):
                flash('密码错误，请输入正确的密码')
            if u.email != form.email_old.data:
                flash('之前的邮箱不正确')
            if User.query.filter(User.email == form.email_new.data).first():
                flash('新邮箱已被其他账号绑定，请更改')
            else:
                u.email = form.email_new.data
                u.confirm = False
                u.save()
                # 获取token字符串
                token = u.generate_token()
                # 发送邮件
                send_mail('邮件激活', u.email, 'activate', username=u.username, token=token,
                          endpoint='user.activate')
                flash('修改成功，请前往邮箱进行账号的激活')
                return redirect(url_for('user.login'))
        except:
            flash('修改失败，请重新修改')
    return render_template('user/change_email.html', form=form)


# 邮件激活的视图函数
@user.route('/activate_password/<token>/', methods=['POST', 'GET'])
def activate_password(token):
    form = NewPassword()
    if User.check_token(token):
        from itsdangerous import TimedJSONWebSignatureSerializer as Seralize  # 导入生成token的模块
        s = Seralize(current_app.config['SECRET_KEY'])
        # 在解析和激活操作过程中，有任何异常都会激活失败
        id = s.loads(token)['id']
        if form.validate_on_submit():
            u = User.query.get(int(id))
            u.password = form.password.data
            User.save(u)
            flash('修改成功，请登录')
            return redirect(url_for('user.login'))
        return render_template('user/password_recover.html', form=form)
    else:
        flash('找回密码失败')
    return render_template('user/password_recover.html', form=form)


@user.route('/recover_password/', methods=['POST', 'GET'])
def recover_password():
    form = Recover_password()
    if form.validate_on_submit():
        u = User.query.filter(User.email == form.email.data).first()
        if not u:
            flash('邮箱不正确')
            return redirect(url_for('user.login'))
        else:
            # 获取token字符串
            token = u.generate_token()
            # 发送邮件
            send_mail('邮件激活', u.email, 'activate_password', username=u.username, token=token,
                      endpoint='user.activate_password')
            flash('修改密码邮件已发送，请去邮箱确认')
            return redirect(url_for('user.login'))
    return render_template('user/recover_password.html', form=form)


# @user.route('/password_recover/')
# def password_recover():
#     form = NewPassword()
#     pass

blog/app/templates/common/base.html
{% extends 'bootstrap/base.html' %}
{% block navbar %}
        <a href="{{ url_for('main.index') }}">
        <div style="height: 50px; color: blue; font-size: 40px; margin-left: 80px">学习记录博客</div>
            <div style="font-size: 40px; height: 50px; color: blue; margin-left: 160px">新手，学习中</div></a>

    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">博客</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="{{ url_for('main.index') }}">首页<span
                            class="sr-only">(current)</span></a></li>
                    <li><a href="{{ url_for('posts.send_posts') }}">发表博客</a></li>
                    {#                    <li class="dropdown">#}
                    {#                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"#}
                    {#                           aria-expanded="false">个人信息 <span class="caret"></span></a>#}
                    {#                        <ul class="dropdown-menu">#}
                    {#                            <li><a href="#">个人信息</a></li>#}
                    {#                            <li><a href="#">修改密码</a></li>#}
                    {#                            <li><a href="#">修改信息</a></li>#}
                    {#                            <li role="separator" class="divider"></li>#}
                    {#                            <li><a href="#">占位</a></li>#}
                    {#                            <li role="separator" class="divider"></li>#}
                    {#                            <li><a href="#">退出登陆</a></li>#}
                    {#                        </ul>#}
                    {#                    </li>#}
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    <form class="navbar-form navbar-left" method="post" action="{{ url_for('posts.search') }}">
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="搜索" name="search">
                        </div>
                        <button type="submit" class="btn btn-default">搜索</button>
                    </form>
                    {#                    判断当前是否处于登录状态#}
                    {% if current_user.is_authenticated %}
                        <li><a>欢迎：{{ current_user.username }}</a></li>
                    {% else %}
                        <li><a href="{{ url_for('user.login') }}">登陆</a></li>
                    {% endif %}

                    <li><a href="{{ url_for('user.register') }}">注册</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                           aria-haspopup="true"
                           aria-expanded="false">个人信息 <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{{ url_for('user.my_info') }}">个人信息</a></li>
                            <li><a href="{{ url_for('user.change_username') }}">修改账号</a></li>
                            <li><a href="{{ url_for('user.change_password') }}">修改密码 </a></li>
                            <li><a href="{{ url_for('user.change_icon') }}">修改头像 </a></li>
                            <li><a href="{{ url_for('user.change_email') }}">修改邮箱 </a></li>
                            <li><a href="{{ url_for('owncenter.posts_manager') }}">我的博客 </a></li>
                            <li><a href="{{ url_for('owncenter.my_attention') }}">我的收藏 </a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="{{ url_for('user.logout') }}">退出登陆</a></li>
                        </ul>
                    </li>

                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
{%- endblock navbar %}
{% block content %}
    <div class="container">

        {% for info in get_flashed_messages() %}
            <div class="alert alert-warning alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                {{ info }}
            </div>
        {% endfor %}

        {% block page_content %}

        {% endblock %}
    </div>
{% endblock %}
{% block scripts %}
    {{ super() }}
    {{ moment.include_moment() }}
    {{ moment.locale('zh-CN') }}
{% endblock %}

blog/app/templates/common/page_macro.html
{% macro page_macro(endpoint, pagination) %}
    <center>
        <nav aria-label="Page navigation">
            <ul class="pagination">
                {#        判断是否有上一页，如果没有则禁用#}
                <li {% if not pagination.has_prev %} class="disabled" {% endif %}>
                    <a {% if pagination.has_prev %}href="{{ url_for(endpoint, page=
                    pagination.prev_num, **kwargs) }}" {% endif %} aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>

                {% for page in pagination.iter_pages() %}
                    {#                active显示页码激活状态#}
                    <li {% if page==pagination.page %} class="active"{% endif %}><a
                            href="{{ url_for(endpoint, page=page, **kwargs) }}">{{ page }}</a></li>
                {% endfor %}

                {#        判断是否有下一页，如果没有则禁用#}
                <li  {% if not pagination.has_next %} class="disabled" {% endif %}>
                    <a {% if pagination.has_next %}href="{{ url_for(endpoint, page=
                    pagination.next_num, **kwargs) }}" {% endif %}aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            </ul>
        </nav>
    </center>
{% endmacro %}

blog/app/templates/common/show_commect_macro.html
{% macro show_comment_macro(endpoint,p, moment) %}
    <center>

    <div class="media-body">
        {{ p.article|safe }}
    </div>
    <br>
    <br>
    <span style="float: right">
        <p><span>作者：{{ p.comment_user.username }}</span></p>
        <P><span>发表时间：{{ moment(p.timestamp).format('Y-M-D H:m:s') }}</span></p>
    </span>


{#{% endblock %}#}
    </center>
{% endmacro %}